# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JulienBlanchon.Xivly
PackageVersion: 0.5.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Xivly
AppsAndFeaturesEntries:
- DisplayName: Xivly
  Publisher: blanchon
  ProductCode: Xivly
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Xivly'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/julien-blanchon/xivly/releases/download/v0.5.0/Xivly_0.5.0_x64-setup.exe
  InstallerSha256: EC61BD538EEA30EC0A22D30178127721D5683098D66CAB1546B05E086581C8EA
ManifestType: installer
ManifestVersion: 1.12.0
